

export const ProjectList: ProjectsListType[] = [
  {
    category: "front-end",
    name: "Landing Page",
    codeUrl: "https://github.com/Swadeshit27/Landing_page",
    demoUrl: "https://calendly-landing-page.vercel.app",
    details: "A landing page is a specialized web page designed to convert visitors into leads or customers. It highlights key information with a clean, engaging design, and features a compelling call-to-action. Its primary goal is to capture user interest and encourage them to take a specific action, such as signing up or visit our page",
    techTools: ["React js", "Vite Js", "Tailwind CSS", "Typescript", "Responsive Design"],
    imgUrl: "/Projects/landing.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "Home page UI",
    codeUrl: "https://github.com/Swadeshit27/Home_page_UI.git",
    demoUrl: "https://home-page-ui-seven.vercel.app/",
    details: "A Home page UI is a specialized web page designed to convert visitors into leads or customers. It highlights key information with a clean, engaging design, and smooth animation. Its primary goal is to capture user interest and encourage them to take a specific action, such as signing up or visit our page",
    techTools: ["React js", "vite js", "Tailwind CSS", "Typescript", "Framer Motion"],
    imgUrl: "/Projects/home_page_UI.png",
    isBest: true,
  },
  {
    category: "fullstack",
    name: "Email Authentication",
    codeUrl: "https://github.com/Swadeshit27/Email-Authentication",
    demoUrl: "https://email-authentication-nine.vercel.app",
    details: "Email authentication website uses email and password for user registration and login. Upon registration, users receive a verification link sent to their registered email. Clicking this link confirms their account, ensuring security and validity. This process protects user data and prevents unauthorized access.User have to upload their photo and choose interest while registering",
    techTools: ["MERN stack", "Tailwind css", "nodemailer", "cloudinary", "formik-yup"],
    imgUrl: "/Projects/authencation.png",
    isBest: true,
  },
  {
    category: "fullstack",
    name: "e-comerce website",
    codeUrl: "https://github.com/Swadeshit27/SWA-CART_ecommerce_website.git",
    demoUrl: "https://e-commerse-front-end.vercel.app",
    details: "E-commerce website facilitates online shopping by offering a wide range of products. Users can browse, search,filter, and purchase items securely. Features include product descriptions, reviews, a shopping cart, and secure payment options. Efficient navigation and personalized recommendations enhance the shopping experience, making it convenient and user-friendly.",
    techTools: ["MERN stack", "Tailwind css", "redux toolkit", "forkik - yup", "redux-persist", "razorpay",],
    imgUrl: "/Projects/ecommerce website.png",
    isBest: true,
  },
  {
    category: "collegeProjects",
    name: "CFI JGEC website",
    codeUrl: "https://github.com/cfi-jgec/cfi-jgec.git",
    demoUrl: "https://cfi-jgec.vercel.app",
    details: "The Center for Innovation  website is our college's platform for showcasing the club's activities and achievements. As a developer, I help present the club's innovative projects and events to the public. The website aims to inspire creativity and collaboration among students, encouraging them to join and show their innovative ideas to the nation",
    techTools: ["Next js 13", "Material UI", "Framer Motion"],
    imgUrl: "/Projects/cfi_jgec.png",
    isBest: false,
  },
  {
    category: "collegeProjects",
    name: "SRISTI Techfest website",
    codeUrl: "https://sristi-2k23-website.vercel.app",
    demoUrl: "https://github.com/SRISTI-JGEC/SRISTI_2K23_Website.git",
    details: "SRISTI is our college's tech fest, a celebration of innovation and technology. As the team leader, I assembled a team of six passionate individuals. Together, we developed a dynamic and engaging website that beautifully showcases all events, complete with detailed descriptions, rules, participant information, and highlights of winners.Our goal is to capture the spirit of SRISTI and inspire excitement and participation in this remarkable event.",
    techTools: ["Next js", "Tailwind css", "TypeScript",],
    imgUrl: "/Projects/Sristi.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "Sport Card Design",
    codeUrl: "https://github.com/Swadeshit27/Sport-Card",
    demoUrl: "https://sport-card-xi.vercel.app",
    details: "Sports card website is an online platform where collectors buy, sell, and trade sports cards. It offers a wide range of cards featuring athletes from various sports, detailed listings, and secure transactions. The site often includes forums, price guides, and community features to enhance the collector experience.",
    techTools: ["Next js 14", "Tailwind CSS", "Typescript",],
    imgUrl: "/Projects/sportcard.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "textUtils website",
    codeUrl: "https://github.com/Swadeshit27/TextUtils-App.git",
    demoUrl: "https://swadeshit27.github.io/TextUtils-App",
    details: "TextUtils website is a font end web application where user can do several operations like uppercase letters, lowercase letters, copy text, delete extra spaces on input text.",
    techTools: ["React js", "Bootstrap"],
    imgUrl: "/Projects/textutils.png",
    isBest: false,
  },
 

  {
    category: "fullstack",
    name: "Invoice Generator",
    codeUrl: "https://github.com/Swadeshit27/Invoice-Generator",
    demoUrl: "https://invoice-generator-five-alpha.vercel.app",
    details: "Invoice generator simplifies billing by creating professional invoices quickly and accurately. Users first create an account and log in. Then add product details by entering the product name, quantity, and price. Finally, the tool generates an invoice for these products, download the invoice also.",
    techTools: ["MERN stack", "Typescript", "redux toolkit", "redux-persist", "Tailwind CSS", "pdfkit", "flowbite react"],
    imgUrl: "/Projects/textutils.png",
    isBest: false,
  },
  {
    category: "fullstack",
    name: "Doctor's appointment",
    codeUrl: "https://github.com/Swadeshit27/Doctor_Appointment-frontend.git",
    demoUrl: "https://doctor-appointment-frontend.vercel.app",
    details: "Doctor's appointment website enables patients to schedule appointments with healthcare professionals online. Users can browse available doctors, view their specialties, and select convenient appointment slots.",
    techTools: ["MERN stack", "Bootstrap", "Redux"],
    imgUrl: "/Projects/docta.png",
    isBest: false,
  },
  {
    category: "fullstack",
    name: "weather reports",
    codeUrl: "https://github.com/Swadeshit27/Full-Authorized-Weather-App.git",
    demoUrl: "",
    details: "Weather report website provides up-to-date weather information, including current conditions like temperature, weather conditions, wind speed, humidity etc.User can check their weather reports by searching their city name",
    techTools: ["React js", "Bootstrap", "handelbars", "Node js", "express js", "mongodb"],
    imgUrl: "/Projects/fullstackWeather.png",
    isBest: false,
  },
  {
    category: "collegeProjects",
    name: "NSS JGEC website",
    codeUrl: "https://github.com/nss-jgec/react-client",
    demoUrl: "https://nss-jgec.vercel.app",
    details: "The National Service Scheme (NSS) is our college's NSS Club website, where I work as a front-end developer. The website showcases the club's work to the nation and encourages young people to join the community. It highlights various activities, projects, and events organized by the club, inspiring youth participation and engagement.",
    techTools: ["React js", "Tailwind css"],
    imgUrl: "/Projects/nss_jgec.png",
    isBest: false,
  },
  {
    category: "app",
    name: "HungerHub App",
    codeUrl: "https://github.com/Swadeshit27/HUNGERHUB-Food_order_app",
    demoUrl: "https://drive.google.com/file/d/1L6stp7c7zGrkWKqA0sqYGxHvHeVMjIZb/view?usp=sharing",
    details: "HungerHub is a food delivery app using React Native. Here user first have to create their account then they can choose various food or filter them by catagories. Cart their products and place their products. Though this is not yet fully completed.",
    techTools: ["React Native", "Styled Components", "formik-yup", "node js", "express js", "mongodb"],
    imgUrl: "/Projects/hungerhub app.jpg",
    isBest: false,
  },
  {
    category: "front-end",
    name: "News website",
    codeUrl: "https://github.com/Swadeshit27/News-App",
    demoUrl: "https://news-app-vdju-oyy8i4tub-swadeshit27.vercel.app/",
    details: "News website delivers timely updates and in-depth coverage on current events. It features diverse categories, from politics and technology to entertainment and sports, ensuring comprehensive reporting.",
    techTools: ["React js", "Bootstrap", "News api"],
    imgUrl: "/Projects/news.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "advance to-do list",
    codeUrl: "https://github.com/Swadeshit27/advance-ToDo-List",
    demoUrl: "https://advance-to-do-list.vercel.app/",
    details: "Advance to-do list website helps users organize tasks efficiently. It offers features like task creation, categorization, deadlines, and reminders. With a clean interface, it enhances productivity by allowing users to prioritize and track their progress, ensuring nothing important is forgotten.",
    techTools: ["React js", "responsive design"],
    imgUrl: "/Projects/todoList.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "Weather Reports",
    codeUrl: "https://github.com/Swadeshit27/Weather-App.git",
    demoUrl: "https://swadeshit27.github.io/Weather-App",
    details: "Weather report website provides up-to-date weather information, including current conditions like temperature, weather conditions, wind speed, humidity etc.User can check their weather reports by searching their city name",
    techTools: ["HTML", "CSS", "JavaScript", "Weather api"],
    imgUrl: "/Projects/weatherReports.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "Music website",
    codeUrl: "https://github.com/Swadeshit27/Music_website.git",
    demoUrl: "https://swadeshit27.github.io/Music_website",
    details: "Music player website allows users to stream and enjoy music. It features a user-friendly interface, customizable playlists, play-pause, repeat-shuffle  and search functionality to explore diverse songs.Also dark and light feature is available ",
    techTools: ["HTML5", "CSS3", "JavaScript"],
    imgUrl: "/Projects/music.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "Portfolio website",
    codeUrl: "https://github.com/Swadeshit27/Portfolio-website",
    demoUrl: "https://swadeshit27.github.io/Portfolio-website",
    details: "My first portfolio website make using HTML,CSS and javascript. Overall website is responsive and user friendly. Dark and light mode also available ",
    techTools: ["HTML5", "CSS3", "JavaScript"],
    imgUrl: "/Projects/portfolio1.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "Calculator",
    codeUrl: "https://github.com/Swadeshit27/Calculator.git",
    demoUrl: "https://swadeshit27.github.io/Calculator",
    details: "Calculator website provides users with various calculation tools, basic arithmetic. It's designed for quick, accurate calculations, featuring a user-friendly interface.",
    techTools: ["HTML5", "CSS3", "JavaScript"],
    imgUrl: "/Projects/calculator.png",
    isBest: false,
  },
  // {
  //   category: "back-end",
  //   name: "Food app backend",
  //   codeUrl: "https://github.com/Swadeshit27/Food-Delivery-App-backend",
  //   demoUrl: "",
  //   details: "",
  //   techTools: ["Node js", "express js", "mongodb"],
  //   imgUrl: "/Projects/",
  //   isBest: false,
  // },
  // {
  //   category: "back-end",
  //   name: "Admin_panel",
  //   codeUrl: "https://github.com/Swadeshit27/Admin_Panel.git",
  //   demoUrl: "",
  //   details: "",
  //   techTools: ["Node js", "express js", "mongodb"],
  //   imgUrl: "/Projects/",
  //   isBest: false,
  // },
]
