

export const ProjectList: ProjectsListType[] = [
  {
    category: "front-end",
    name: "Landing Page",
    codeUrl: "https://github.com/Swadeshit27/Landing_page",
    demoUrl: "https://calendly-landing-page.vercel.app",
    details: "",
    techTools: ["React js", "Tailwind CSS", "Typescript", "Framer Motion"],
    imgUrl: "/Projects/landing.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "Home page UI",
    codeUrl: "https://github.com/Swadeshit27/Home_page_UI.git",
    demoUrl: "https://home-page-ui-seven.vercel.app/",
    details: "",
    techTools: ["React js", "Tailwind CSS", "Typescript", "Framer Motion"],
    imgUrl: "/Projects/home_page_UI.png",
    isBest: true,
  },
  {
    category: "front-end",
    name: "Sport Card Design",
    codeUrl: "https://github.com/Swadeshit27/Sport-Card",
    demoUrl: "https://sport-card-xi.vercel.app",
    details: "",
    techTools: ["React js", "Tailwind CSS", "Typescript", "Framer Motion"],
    imgUrl: "/Projects/sportcard.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "advance to-do list",
    codeUrl: "https://github.com/Swadeshit27/News-App",
    demoUrl: "https://news-app-vdju-oyy8i4tub-swadeshit27.vercel.app/",
    details: "",
    techTools: ["React js", "Bootstrap", "News api"],
    imgUrl: "/Projects/todoList.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "Music website",
    codeUrl: "https://github.com/Swadeshit27/Music_website.git",
    demoUrl: "https://swadeshit27.github.io/Music_website",
    details: "",
    techTools: ["HTML", "CSS", "JavaScript"],
    imgUrl: "/Projects/music.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "Calculator",
    codeUrl: "https://github.com/Swadeshit27/Calculator.git",
    demoUrl: "https://swadeshit27.github.io/Calculator",
    details: "",
    techTools: ["HTML", "CSS", "JavaScript"],
    imgUrl: "/Projects/calculator.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "Weather Reports",
    codeUrl: "https://github.com/Swadeshit27/Weather-App.git",
    demoUrl: "https://swadeshit27.github.io/Weather-App",
    details: "",
    techTools: ["HTML", "CSS", "JavaScript", "Weather api"],
    imgUrl: "/Projects/weatherReports.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "textUtils website",
    codeUrl: "https://github.com/Swadeshit27/TextUtils-App.git",
    demoUrl: "https://swadeshit27.github.io/TextUtils-App",
    details: "",
    techTools: ["React js", "Bootstrap"],
    imgUrl: "/Projects/textutils.png",
    isBest: false,
  },
  {
    category: "front-end",
    name: "News website",
    codeUrl: "https://github.com/Swadeshit27/News-App",
    demoUrl: "https://news-app-vdju-oyy8i4tub-swadeshit27.vercel.app/",
    details: "",
    techTools: ["React js", "Bootstrap", "News api"],
    imgUrl: "/Projects/news.png",
    isBest: false,
  },
  {
    category: "fullstack",
    name: "Email Authentication",
    codeUrl: "https://github.com/Swadeshit27/Email-Authentication",
    demoUrl: "https://email-authentication-nine.vercel.app",
    details: "",
    techTools: ["React js", "Tailwind css", "Node js", "express js", "mongodb"],
    imgUrl: "/Projects/authencation.png",
    isBest: true,
  },
  {
    category: "fullstack",
    name: "e-comerce website",
    codeUrl: "https://github.com/Swadeshit27/SWA-CART_ecommerce_website.git",
    demoUrl: "https://totalitycorp-frontend-challenge-phi.vercel.app",
    details: "",
    techTools: ["React js", "Tailwind css", "Node js", "express js", "mongodb"],
    imgUrl: "/Projects/ecommerce website.png",
    isBest: true,
  },
  {
    category: "fullstack",
    name: "Invoice Generator",
    codeUrl: "https://github.com/Swadeshit27/Invoice-Generator",
    demoUrl: "https://invoice-generator-five-alpha.vercel.app",
    details: "",
    techTools: ["React Js", "Typescript", "redux toolkit", "redux-persist", "Tailwind CSS", "Node js", "express js", "mongodb", "pdfkit"],
    imgUrl: "/Projects/textutils.png",
    isBest: false,
  },
  {
    category: "fullstack",
    name: "Doctor's appointment",
    codeUrl: "https://github.com/Swadeshit27/Doctor_Appointment-frontend.git",
    demoUrl: "https://doctor-appointment-frontend.vercel.app",
    details: "",
    techTools: ["React js", "Bootstrap", "Node js", "express js", "mongodb"],
    imgUrl: "/Projects/textutils.png",
    isBest: false,
  },
  {
    category: "fullstack",
    name: "weather reports",
    codeUrl: "https://github.com/Swadeshit27/Full-Authorized-Weather-App.git",
    demoUrl: "",
    details: "",
    techTools: ["React js", "Bootstrap", "handelbars", "Node js", "express js", "mongodb"],
    imgUrl: "/Projects/fullstackWeather.png",
    isBest: false,
  },
  {
    category: "collegeProjects",
    name: "NSS JGEC website",
    codeUrl: "https://nss-jgec.vercel.app",
    demoUrl: "https://github.com/Swadeshit27/react-client.git",
    details: "",
    techTools: ["React js", "Tailwind css"],
    imgUrl: "/Projects/nss_jgec.png",
    isBest: false,
  },
  {
    category: "collegeProjects",
    name: "CFI JGEC website",
    codeUrl: "https://github.com/cfi-jgec/cfi-jgec.git",
    demoUrl: "https://cfi-jgec.vercel.app",
    details: "",
    techTools: ["Next js", "Material UI", "Framer Motion"],
    imgUrl: "/Projects/cfi_jgec.png",
    isBest: false,
  },
  {
    category: "collegeProjects",
    name: "SRISTI Techfest website",
    codeUrl: "https://sristi-2k23-website.vercel.app",
    demoUrl: "https://github.com/SRISTI-JGEC/SRISTI_2K23_Website.git",
    details: "",
    techTools: ["Next js", "Tailwind css", "TypeScript",],
    imgUrl: "/Projects/Sristi.png",
    isBest: false,
  },
  {
    category: "back-end",
    name: "Admin_panel",
    codeUrl: "https://github.com/Swadeshit27/Admin_Panel.git",
    demoUrl: "",
    details: "",
    techTools: ["React js", "Tailwind css", "Node js", "express js", "mongodb"],
    imgUrl: "/Projects/",
    isBest: false,
  },
  {
    category: "ui/ux",
    name: "",
    codeUrl: "",
    demoUrl: "",
    details: "",
    techTools: [""],
    imgUrl: "",
    isBest: false,
  }
]
